# Generated by Django 5.2.17 on 2026-09-14 10:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Railway Station',
                'verbose_name_plural': 'Railway Stations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='stations_st_name_1d3a22_idx'), models.Index(fields=['name_en'], name='stations_st_name_en_ff379d_idx')],
            },
        ),
    ]
