# Generated by Django 5.2.17 on 2026-09-15 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('ARRIVED', 'Arrived at station'), ('DEPARTED', 'Departed from station'), ('PASSED', 'Passed through'), ('ISSUE', 'Issue')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='trains.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='ReportVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('RIGHT', 'Right'), ('WRONG', 'Wrong')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['train', '-event_time'], name='report_train_time_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['station', '-event_time'], name='report_station_time_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-event_time'], name='report_event_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportvote',
            constraint=models.UniqueConstraint(fields=('report', 'user'), name='unique_user_report_vote'),
        ),
    ]
