"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

import os
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# GIS LIBRARIES - Windows / QGIS
# =============================================================================
if os.name == "nt":
    QGIS_ROOT = r"C:\Program Files\QGIS 4.2.1"
    QGIS_BIN = os.path.join(QGIS_ROOT, "bin")
    QGIS_PROJ = os.path.join(QGIS_ROOT, "share", "proj")

    QGIS_DLL_DIR = os.add_dll_directory(QGIS_BIN)

    GDAL_LIBRARY_PATH = os.path.join(
        QGIS_BIN,
        "gdal313.dll",
    )

    GEOS_LIBRARY_PATH = os.path.join(
        QGIS_BIN,
        "geos_c.dll",
    )

    os.environ["PROJ_LIB"] = QGIS_PROJ



# ==============================================
# security section
# ==============================================
SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv("DEBUG", 'False').lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", '').split(",")
    if host.strip()
]



# ==============================================
# Application Defination section
# ==============================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # geodjango
    'django.contrib.gis',

    # third party
    "rest_framework",
    "corsheaders",
    "leaflet",
    'silk',

    # local apps
    "accounts",
    "stations",
    'trains',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'silk.middleware.SilkyMiddleware',
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==============================================
# Auth Useer section
# ==============================================
AUTH_USER_MODEL = 'accounts.User'


# =========================================================
# Databaase section
# =========================================================
DATABASES = {
    "default" : {
        "ENGINE" : "django.contrib.gis.db.backends.postgis",
        "NAME" : os.getenv("DB_NAME"),
        'USER' : os.getenv("DB_USER"),
        "PASSWORD" : os.getenv("DB_PASSWORD"),
        "HOST" : os.getenv("DB_HOST"),
        "PORT" : os.getenv("DB_PORT"),
    }
}


# =========================================================
# Auth Passwordd section
# =========================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# ==============================================
# Internationalization section
# ==============================================
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# ==============================================
# Static section
# ==============================================
STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# =========================================================
# Default primary key section
# =========================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================================================
# Corsheaders section
# =========================================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


# =========================================================
# leaflet config section
# =========================================================
LEAFLET_CONFIG = {
    "DEFAULT_CENTER": (23.8103, 90.4125),
    "DEFAULT_ZOOM": 7,
}


# ==============================================
# Rest framework confnign
# ==============================================
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}